#' clump_bycategory
#' 
#' create patches with unique ids for spatially contigous areas with the same value
#' @param basemap a raster map values should be integer (e.g use round) for clumping
#' @param direction (default 8) direction for clumping
#' 
#' @return raster with same coordinates/dimensions as basemap with clump ids
#' 
clump_bycategory = function(basemap, directions=8 ) {
  ucats = unique(basemap)
  lgall=NULL
  crmax=0
  
  
  # combine continugous cells for each possible category and store in a data frame
  for (i in 1:length(ucats)) {
    tmp = raster::overlay(basemap, fun=function(x) { a = ifelse(x==ucats[i],1,0); return(a)})
    tmp2 = raster::clump(tmp, directions=directions)
    lg = as.data.frame(rasterToPoints(tmp2))
    # rename to generate unique clump IDs
    lg$clumps = lg$clumps+crmax
    lgall = rbind.data.frame(lgall,lg)
    crmax=max(lgall$clumps)
  }
  
  # define a mode function
  getmode = function(v, na.rm=TRUE) {
    uniqv <- unique(v)
    uniqv <- subset(uniqv, !is.na(uniqv))
    uniqv[which.max(tabulate(match(v, uniqv)))]
  }
  
  #generate raster from points data frame generated by clump
  res = raster::rasterize(lgall[,c("x","y")], basemap, lgall$clumps, fun=getmode)
  return(res)
}