name: Build Docker

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t lgraup/rhessys .
    - name: Login to Docker
      run: docker login -u lgraup --p LGdrummer94
    - name: Update repository
      run: docker push lgraup/rhessys

